// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRi0IuCWnNNUnZfwk7dUke5_bG3fnHSM',
    appId: '1:816470317389:web:7bf6334d32c4b7ebfdff04',
    messagingSenderId: '816470317389',
    projectId: 'coctelmj',
    authDomain: 'coctelmj.firebaseapp.com',
    storageBucket: 'coctelmj.appspot.com',
    measurementId: 'G-HHRV7VEQ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ngZPVh8WBwb6aenK_ZzH82_5AsMMTsQ',
    appId: '1:816470317389:android:004a0f92386549dafdff04',
    messagingSenderId: '816470317389',
    projectId: 'coctelmj',
    storageBucket: 'coctelmj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSsv9Lmf0HCvgO1EGl-Ogy2IWIFNpvyEo',
    appId: '1:816470317389:ios:64bec2125492c722fdff04',
    messagingSenderId: '816470317389',
    projectId: 'coctelmj',
    storageBucket: 'coctelmj.appspot.com',
    iosClientId: '816470317389-02hhrbtnia547pt9v4jtpm84vunek1qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.coctelmj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSsv9Lmf0HCvgO1EGl-Ogy2IWIFNpvyEo',
    appId: '1:816470317389:ios:64bec2125492c722fdff04',
    messagingSenderId: '816470317389',
    projectId: 'coctelmj',
    storageBucket: 'coctelmj.appspot.com',
    iosClientId: '816470317389-02hhrbtnia547pt9v4jtpm84vunek1qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.coctelmj',
  );
}
